language: cpp
compiler: gcc
before_install: sudo apt-get install libconfig++-dev libboost-dev libboost-thread-dev autoconf-archive
before_script:
  - mkdir -p m4
  - autoreconf -fi
  - ./configure
script: make -C tests && make -C tests check-TESTS && sudo make install
